export default [
  {
    ignores: [
      "android/**",
      "ios/**",
      "dist/**",
      "node_modules/**",
      "src/App-backup*.jsx",
      "src/App.j",
      "src/pilateacher-shell-schedule.jsx",
    ],
  },
  {
    files: ["src/ai/**/*.js", "src/data/**/*.js", "src/features/auth/**/*.js", "src/features/account/**/*.js", "tools/**/*.js", "tests/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        Buffer: "readonly",
        AbortController: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        fetch: "readonly",
        process: "readonly",
        setTimeout: "readonly",
        structuredClone: "readonly",
        URL: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unreachable": "error",
      "no-dupe-keys": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
    },
  },
  {
    files: ["src/**/*.{js,jsx}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: {
        Blob: "readonly",
        CustomEvent: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        MediaRecorder: "readonly",
        ResizeObserver: "readonly",
        TextEncoder: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        caches: "readonly",
        console: "readonly",
        createImageBitmap: "readonly",
        crypto: "readonly",
        document: "readonly",
        fetch: "readonly",
        indexedDB: "readonly",
        localStorage: "readonly",
        navigator: "readonly",
        performance: "readonly",
        process: "readonly",
        requestAnimationFrame: "readonly",
        setInterval: "readonly",
        setTimeout: "readonly",
        structuredClone: "readonly",
        window: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unreachable": "error",
      "no-dupe-keys": "error",
    },
  },
];
