export const ONBOARD_SAMPLE_SESSION = Object.freeze({
  key: "onboarding-session-preview",
  date: "2026-09-05",
  startTime: "10:00",
  type: "개인레슨",
  today: "리포머",
  change: "",
  reaction: "허리가 편해졌다고 함",
  next: "캐딜락으로 흉추",
  source: "ai",
  confirmationState: "confirmed",
  confirmedAt: "",
  confirmedCount: 1,
  confirmableCount: 1,
  records: [],
  lesson: null,
  warning: "",
  sourceDateHint: "",
});
